### PR TITLE
Reorganize docker build to facilitate subpackages being in individual repos

### PR DESCRIPTION
**Pull request by cuttlefish**
~This is still a work in progress, but I'd like some eyes on it.~
I'm hoping that it will streamline making images for each subpackage.
I had some issues with the rasterio package binaries being installed, even when it's listed in the `no-binaries`. I've forced the fix in the docker images, but it might arise in other environments.

### CODE REVIEW

**Comment by cuttlefish** [comment]
Mixing pip and conda seems dangerous to me. Should we be using conda for dependencies? Maybe just for rasterio? The Dockerfile would be slightly simplified if rasterio didn't need to be built from source.

**Comment by gadomski** [comment]
> Mixing pip and conda seems dangerous to me.

I agree it's not ideal, but there are some [docs](https://www.anaconda.com/blog/using-pip-in-a-conda-environment) that outline best practices in mixing the two, so it doesn't seem like a huge no-no at least to me.

> Should we be using conda for dependencies? 

We're using conda to get a GDAL that supports HDF4, and leaving the rest up to pip. If there were another way to get a feature-full GDAL build w/o conda I'd be open to it. I will say that personally I use conda as my dev environment because getting the right pythony GDAL set up on OSX can be problematic, so having a conda `environment.yml` in our repo might be a nice thing for some developers?

**Comment by lossyrob** [comment]
I'm experiencing a painpoint in the new subpackage development and wondering if this work will help.

In the subpackage images there's a COPY of the whole source tree early in the build. Which means if anything changes, the requirements are re-installed on rebuild, which usually takes a while (and a lot of CPU). Previous to the subpackage re-org the dockerfile was laid out such that requirements were only installed when the requirements.txt file changed.

Is this work targeting that issue as well, or should I file a separate one?

**Comment by cuttlefish** [comment]
@lossyrob I think it should, but I'll test it. Do you have an example I can compare against?

What I usually do is COPY whatever is needed to install the dependencies (setup.py, requirements.txt, etc), install them, and then COPY the rest of the source. You might duplicate a few small files, but it helps a lot on build times.
The multi-stage build makes it a bit unclear, but that's essentially what I'm doing here: https://github.com/sparkgeo/stactools/blob/8025ed2a07ebddfa3509a1f15101e4f5fc01bb61/docker/Dockerfile#L17-L21
(there's probably a cleaner way to do it than installing the package and removing the package)

**Comment by lossyrob** [comment]
@cuttlefish that's the technique that we were [using here](https://github.com/stac-utils/stactools/blob/v0.1.6/docker/Dockerfile#L49), copying in the requirements and doing an install with just that file. Since we moved away from a requirements file I'm not sure how to accomplish this, so if you've got a solution that would be great even if it trades some complexity for build times.

Really the test is, if I'm in a sub-package like aster, and I make a code change and run `docker/build` - does that re-install requirements or not? If not, we're in a better spot for the docker development environment than currently.

**Comment by cuttlefish** [comment]
@lossyrob 
(this is from my Aster branch)
It seems to be hitting cached layers until the final `pip install` or `pip install -e`. The total time to build both the main and dev containers is ~1.5 seconds, so it can't be reinstalling dependencies.

```
% echo "# modify source\n" >> src/stactools/aster/stac.py
% time docker/build
[+] Building 1.4s (12/12) FINISHED
 => [internal] load build definition from Dockerfile-script-runner                                                                                                                                                                                       0.0s
 => => transferring dockerfile: 213B                                                                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/python:3-buster                                                                                                                                                                                       1.2s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                                                                                                            0.0s
 => [1/6] FROM docker.io/library/python:3-buster@sha256:361fdc5abde0666f8c9be3c53d292928765c4649203d117376c42e0cbd312991                                                                                                                                 0.0s
 => => resolve docker.io/library/python:3-buster@sha256:361fdc5abde0666f8c9be3c53d292928765c4649203d117376c42e0cbd312991                                                                                                                                 0.0s
 => [internal] load build context                                                                                                                                                                                                                        0.0s
 => => transferring context: 810B                                                                                                                                                                                                                        0.0s
 => CACHED [2/6] WORKDIR /opt/aster                                                                                                                                                                                                                      0.0s
 => CACHED [3/6] COPY requirements-dev.txt ./                                                                                                                                                                                                            0.0s
 => CACHED [4/6] RUN pip install -r requirements-dev.txt                                                                                                                                                                                                 0.0s
 => CACHED [5/6] COPY scripts/ scripts/                                                                                                                                                                                                                  0.0s
 => CACHED [6/6] COPY docker/ docker/                                                                                                                                                                                                                    0.0s
 => exporting to image                                                                                                                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                                                                                                                  0.0s
 => => writing image sha256:1020ab6e6f058b80f65b531c71bc85107a1b59fe007888e4a60e7ba52774ddec                                                                                                                                                             0.0s
 => => naming to docker.io/library/stactools-aster-script-runner                                                                                                                                                                                         0.0s
Building with stactools version 0.2.1a1
[+] Building 5.2s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                     0.0s
 => => transferring dockerfile: 426B                                                                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/stacutils/stactools:0.2.1a1                                                                                                                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                                                                        0.0s
 => => transferring context: 55.83kB                                                                                                                                                                                                                     0.0s
 => [1/7] FROM docker.io/stacutils/stactools:0.2.1a1                                                                                                                                                                                                     0.0s
 => CACHED [2/7] WORKDIR /opt/aster                                                                                                                                                                                                                      0.0s
 => CACHED [3/7] COPY pyproject.toml setup.cfg ./                                                                                                                                                                                                        0.0s
 => CACHED [4/7] COPY src/stactools/aster/__init__.py src/stactools/aster/                                                                                                                                                                               0.0s
 => CACHED [5/7] RUN pip install .     && rm -r /opt/conda/lib/python3.8/site-packages/stactools/aster                                                                                                                                                   0.0s
 => [6/7] COPY src ./src                                                                                                                                                                                                                                 0.0s
 => [7/7] RUN pip install .                                                                                                                                                                                                                              5.0s
 => exporting to image                                                                                                                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                                                                                                                  0.0s
 => => writing image sha256:c8ce6e859c5d077c060cdd46f7bc9b1a1639297a7b9f5bb89be89980a694c3af                                                                                                                                                             0.0s
 => => naming to docker.io/stacutils/stactools-aster:latest                                                                                                                                                                                              0.0s
[+] Building 8.2s (12/12) FINISHED
 => [internal] load build definition from Dockerfile-dev                                                                                                                                                                                                 0.0s
 => => transferring dockerfile: 500B                                                                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/stacutils/stactools:0.2.1a1-dev                                                                                                                                                                               0.0s
 => [1/7] FROM docker.io/stacutils/stactools:0.2.1a1-dev                                                                                                                                                                                                 0.0s
 => [internal] load build context                                                                                                                                                                                                                        1.6s
 => => transferring context: 134.53MB                                                                                                                                                                                                                    1.6s
 => CACHED [2/7] WORKDIR /opt/aster                                                                                                                                                                                                                      0.0s
 => CACHED [3/7] COPY pyproject.toml requirements-dev.txt setup.cfg ./                                                                                                                                                                                   0.0s
 => CACHED [4/7] COPY src/stactools/aster/__init__.py src/stactools/aster/                                                                                                                                                                               0.0s
 => CACHED [5/7] RUN pip install -r requirements-dev.txt     && pip install .     && rm -r /opt/conda/lib/python3.8/site-packages/stactools/aster                                                                                                        0.0s
 => [6/7] COPY . ./                                                                                                                                                                                                                                      0.3s
 => [7/7] RUN pip install -e .                                                                                                                                                                                                                           5.6s
 => exporting to image                                                                                                                                                                                                                                   0.6s
 => => exporting layers                                                                                                                                                                                                                                  0.6s
 => => writing image sha256:b446525bf83f428dcc9bb67b42845599b85881973678eb83dc215912d7ac599d                                                                                                                                                             0.0s
 => => naming to docker.io/stacutils/stactools-aster:latest-dev                                                                                                                                                                                          0.0s
docker/build  1.37s user 1.11s system 14% cpu 17.331 total
```

**Comment by cuttlefish** [comment]
I don't have permissions in this repo to setup secrets or anything, so I can't setup Actions to build and push the images to Docker Hub. I'm pushing them manually at the moment.

**Review by gadomski — APPROVED** [review]

**Comment by gadomski** [comment]
@lossyrob can you set up secrets w/ Tyler to push these to Docker Hub?

**Pull request merged**
