### PR TITLE
Add publish-location argument to copy command

### PR DESCRIPTION
**Pull request by volaya**
This PR adds the functionality described in #12 

It requires the changes in pystac proposed in https://github.com/stac-utils/pystac/pull/565

### CODE REVIEW

**Review by gadomski — CHANGES_REQUESTED** [review]
Can you add a unit test? Thanks!

**Review by gadomski — APPROVED** [review]
LGTM, this seems really useful, thanks for adding!

**EDIT:** CI is failing though so that'll need to be fixed before merge.

**Comment by volaya** [comment]
CI failure seems to be happen because the required changes in pystac are not available. The corresponding PR is merged, but the changes are still not in the version that the CI gets from pip to setup the environment.

**Comment by gadomski** [comment]
Roger, once PySTAC v1.0.1 hits the shelves we'll re-run CI here and in #153 to keep things moving along. Thanks!

**Comment by cuttlefish** [comment]
`PySTAC version 1.0.1` but it's still failing. I haven't had a chance to track down why.

**Comment by gadomski** [comment]
@volaya stac-utils/pystac@6ba134f603ef069e88daf8123bb52908dd64263c isn't included in PySTAC v1.0.1 because it is an (backwards-compatible) API change. My guess is that it will be included in PySTAC v1.1, whenever that is released. My initial instinct is to triage this pull request into a `pystac-v1.1` milestone that will be merged into stactools **main** branch once PySTAC version v1.1 is released. Any issues with that approach?

**Comment by volaya** [comment]
That sounds good to me!

**Review by gadomski — APPROVED** [review]

**Pull request merged**
